import type { Metadata } from "next";
import { Rubik_80s_Fade, Agbalumo, Rubik, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { ReactQueryConfig } from "@/config/react-query";
import { StoreProvider } from "@/components/store-provider/store-provider";

const inter = Agbalumo({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryConfig>
            {children}
          </ReactQueryConfig>
        </body>
      </html>
    </StoreProvider>
  );
}
